version: '3'
services:

  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - db-net
    environment:
      MYSQL_ROOT_PASSWORD: secure
      MYSQL_USER: shop
      MYSQL_PASSWORD: shoppw
      MYSQL_DATABASE: shop

  im.shop:
    image: webdevops/php-nginx:7.3
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./www:/app
    links:
      - db
    networks:
      - db-net
    environment:
      WEB_DOCUMENT_ROOT: /app/shop/public

networks:
  db-net:
